import { ProdutoFocus } from './types';

export const DEFAULT_PRODUCTS: ProdutoFocus[] = [
  {
    id: 'prod-erp',
    codigo: 'FOCUS-ERP',
    nome: 'Focus ERP',
    categoria: 'ERP & Gestão',
    descricaoBreve: 'Sistema de gestão empresarial integrado para controle financeiro, faturamento, RH e estoque.',
    descricaoCompleta: 'O Focus ERP é o núcleo de gestão empresarial da Focus Tecnologia. Abrange os módulos de Fluxo de Caixa, Contas a Pagar e Receber, Faturamento Fiscal, Contratos, RH, DRE e Controle de Estoque e Patrimônio.',
    status: 'Ativo',
    versaoAtual: 'v3.2.0',
    responsavelPrincipal: 'Carlos Andrade (Head of Product)',
    dataLancamento: '2023-01-15',
    siteOficial: 'https://focustecnologia.com.br/erp',
    repositorioGit: 'https://github.com/focustecnologia/focus-erp',
    documentacaoUrl: 'https://docs.focustecnologia.com.br/erp',
    linksUteis: [
      { id: 'l-1', titulo: 'Ambiente de Produção', url: 'https://focus-financial-insight-main.vercel.app', tipo: 'Produção' },
      { id: 'l-2', titulo: 'Ambiente de Homologação', url: 'https://staging.focustecnologia.com.br', tipo: 'Homologação' },
      { id: 'l-3', titulo: 'Documentação Oficial de APIs', url: 'https://docs.focustecnologia.com.br/api-erp', tipo: 'API' },
      { id: 'l-4', titulo: 'Projeto Figma Design System', url: 'https://figma.com/@focustecnologia/design-system', tipo: 'Figma' },
    ],
    roadmap: [
      { id: 'rm-1', titulo: 'Integração Nativa com Open Finance', descricao: 'Sincronização bancária automática via extrato OFX e API de bancos.', prioridade: 'Alta', status: 'Em Desenvolvimento', responsavel: 'Dev Team ERP', sprint: 'Sprint 24.3', dataPrevista: '2026-08-30' },
      { id: 'rm-2', titulo: 'Emissão Automática de NFSe Multi-cidades', descricao: 'Homologação de prefeituras para faturamento de serviços.', prioridade: 'Crítica', status: 'Planejamento', responsavel: 'Fiscal Lead', sprint: 'Sprint 24.4', dataPrevista: '2026-09-15' },
      { id: 'rm-3', titulo: 'App Mobile para Gestão Financeira', descricao: 'Aplicativo iOS/Android para aprovação de contas a pagar e notificações.', prioridade: 'Média', status: 'Backlog', responsavel: 'Mobile Team', sprint: 'Sprint 24.6', dataPrevista: '2026-11-01' },
    ],
    funcionalidades: [
      { id: 'fn-1', nome: 'Financeiro & Fluxo de Caixa', descricao: 'Gestão de contas a pagar, receber, conciliacao e projecoes', status: 'Ativo', versao: 'v3.2.0', responsavel: 'Finance Team' },
      { id: 'fn-2', nome: 'Comercial & Faturamento', descricao: 'Emissao de propostas, orcamentos e ordens de venda', status: 'Ativo', versao: 'v3.1.0', responsavel: 'Sales Tech' },
      { id: 'fn-3', nome: 'RH & Folha de Pagamento', descricao: 'Controle de colaboradores, ponto e relatorios trabalhistas', status: 'Ativo', versao: 'v2.8.0', responsavel: 'HR Team' },
      { id: 'fn-4', nome: 'Fiscal & SPED', descricao: 'Geracao de impostos, NF-e, NFS-e e SPED Fiscal', status: 'Ativo', versao: 'v3.0.0', responsavel: 'Tax Team' },
      { id: 'fn-5', nome: 'Estoque & Patrimônio (ITAM)', descricao: 'Rastreabilidade de ativos TI, inventario e licencas SaaS', status: 'Ativo', versao: 'v3.2.0', responsavel: 'ITAM Team' },
    ],
    releases: [
      {
        id: 'rel-1',
        versao: 'v3.2.0',
        tipo: 'Major',
        dataPublicacao: '2026-07-24',
        changelog: 'Lançamento do módulo de Estoque & Patrimônio ITAM com rastreamento de licenças SaaS e ativos físicos.',
        novasFuncionalidades: ['Módulo ITAM completo', 'Gestão de Licenças SaaS', 'Cronograma de Manutenção'],
        correcoes: ['Ajuste de proporção do Favicon PWA', 'Melhoria de performance no carregamento de gráficos'],
        responsavel: 'Carlos Andrade',
      },
      {
        id: 'rel-2',
        versao: 'v3.1.0',
        tipo: 'Minor',
        dataPublicacao: '2026-06-10',
        changelog: 'Refatoração da DRE Interativa e DRE Gerencial por Centro de Custo.',
        novasFuncionalidades: ['Exportação de relatórios em Excel/PDF', 'Filtro por competência'],
        responsavel: 'Ana Clara',
      },
    ],
    implementacoes: [],
    integracoes: [
      { id: 'int-1', produtoDestinoId: 'prod-pay', produtoDestinoNome: 'Focus Pay', tipoComunicacao: 'API REST', status: 'Ativa', apiUtilizada: 'v1/payments/checkout', observacoes: 'Geração automática de cobrança PIX e Boleto' },
      { id: 'int-2', produtoDestinoId: 'prod-crm', produtoDestinoNome: 'Focus CRM', tipoComunicacao: 'Webhooks', status: 'Ativa', apiUtilizada: 'v2/webhooks/deals', observacoes: 'Transforma oportunidades ganhas em Contratos ERP' },
      { id: 'int-3', produtoDestinoId: 'prod-bi', produtoDestinoNome: 'Focus BI', tipoComunicacao: 'Banco Compartilhado', status: 'Ativa', apiUtilizada: 'ETL Direct Stream', observacoes: 'Alimentação diária dos cubos de dados financeiros' },
    ],
    equipe: [
      { id: 'eq-1', nome: 'Carlos Andrade', cargo: 'Head of Product', papelNoProduto: 'Product Owner' },
      { id: 'eq-2', nome: 'Mariana Oliveira', cargo: 'Tech Lead Fullstack', papelNoProduto: 'Tech Lead' },
      { id: 'eq-3', nome: 'Lucas Mendes', cargo: 'DevOps & Backend', papelNoProduto: 'Desenvolvedor' },
    ],
    createdAt: '2023-01-15T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'prod-crm',
    codigo: 'FOCUS-CRM',
    nome: 'Focus CRM',
    categoria: 'CRM & Vendas',
    descricaoBreve: 'Plataforma de gestão comercial, pipeline de vendas, automação de cadência e propostas.',
    descricaoCompleta: 'O Focus CRM centraliza toda a jornada de vendas, desde a captação de leads até o fechamento. Conta com kanban comercial personalizável, automação de e-mails, integração com WhatsApp e métricas de conversão.',
    status: 'Ativo',
    versaoAtual: 'v2.1.0',
    responsavelPrincipal: 'Fernanda Lima (Product Manager)',
    dataLancamento: '2023-08-20',
    siteOficial: 'https://focustecnologia.com.br/crm',
    repositorioGit: 'https://github.com/focustecnologia/focus-crm',
    documentacaoUrl: 'https://docs.focustecnologia.com.br/crm',
    linksUteis: [
      { id: 'lc-1', titulo: 'Ambiente do Vendedor', url: 'https://crm.focustecnologia.com.br', tipo: 'Produção' },
      { id: 'lc-2', titulo: 'Documentação de Webhooks', url: 'https://docs.focustecnologia.com.br/crm-webhooks', tipo: 'API' },
    ],
    roadmap: [
      { id: 'rm-crm-1', titulo: 'Automação de WhatsApp via Meta Cloud API', descricao: 'Disparo de mensagens e cadência de vendas automatizada.', prioridade: 'Crítica', status: 'Em Desenvolvimento', responsavel: 'CRM Team', sprint: 'Sprint 18', dataPrevista: '2026-08-20' },
    ],
    funcionalidades: [
      { id: 'fc-1', nome: 'Pipeline Kanban Comercial', descricao: 'Etapas de prospecção, qualificação, proposta e fechamento', status: 'Ativo', versao: 'v2.1.0' },
      { id: 'fc-2', nome: 'Gerador de Propostas Comerciais PDF', descricao: 'Criação de propostas customizadas com assinatura eletrônica', status: 'Ativo', versao: 'v2.0.0' },
    ],
    releases: [
      { id: 'rel-crm-1', versao: 'v2.1.0', tipo: 'Minor', dataPublicacao: '2026-05-15', changelog: 'Inclusão de pontuação de Leads (Lead Scoring com IA).', responsavel: 'Fernanda Lima' },
    ],
    implementacoes: [],
    integracoes: [
      { id: 'int-crm-1', produtoDestinoId: 'prod-erp', produtoDestinoNome: 'Focus ERP', tipoComunicacao: 'Webhooks', status: 'Ativa', apiUtilizada: 'v1/deals/closed-won' },
    ],
    equipe: [
      { id: 'eq-crm-1', nome: 'Fernanda Lima', cargo: 'Product Manager', papelNoProduto: 'Product Owner' },
    ],
    createdAt: '2023-08-20T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'prod-bi',
    codigo: 'FOCUS-BI',
    nome: 'Focus BI',
    categoria: 'Business Intelligence',
    descricaoBreve: 'Central de dashboards analíticos, indicadores executivos e inteligência de dados.',
    descricaoCompleta: 'O Focus BI consolida dados de finanças, vendas, RH e operação em dashboards interativos com gráficos dinâmicos, comparativos anuais e relatórios gerenciais exportáveis.',
    status: 'Ativo',
    versaoAtual: 'v1.8.4',
    responsavelPrincipal: 'Roberto Mansur (Data Lead)',
    dataLancamento: '2024-02-01',
    siteOficial: 'https://focustecnologia.com.br/bi',
    repositorioGit: 'https://github.com/focustecnologia/focus-bi',
    linksUteis: [
      { id: 'lb-1', titulo: 'Painel BI Executivo', url: 'https://bi.focustecnologia.com.br', tipo: 'Produção' },
    ],
    roadmap: [],
    funcionalidades: [
      { id: 'fb-1', nome: 'Dashboards Financeiro & DRE', descricao: 'Consolidação de receitas, despesas e margem EBITDA', status: 'Ativo', versao: 'v1.8.4' },
    ],
    releases: [],
    implementacoes: [],
    integracoes: [],
    equipe: [],
    createdAt: '2024-02-01T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'prod-pay',
    codigo: 'FOCUS-PAY',
    nome: 'Focus Pay',
    categoria: 'Fintech & Pay',
    descricaoBreve: 'Gateway de pagamentos corporativo com checkout transparente, PIX dinâmico e split.',
    descricaoCompleta: 'Solução da Focus para infraestrutura de pagamentos digitais. Permite receber cartão de crédito, PIX QR Code instantâneo com conciliação automática e réguas de cobrança.',
    status: 'Ativo',
    versaoAtual: 'v1.5.0',
    responsavelPrincipal: 'Bruno Souza (Fintech Lead)',
    dataLancamento: '2024-04-10',
    siteOficial: 'https://focustecnologia.com.br/pay',
    repositorioGit: 'https://github.com/focustecnologia/focus-pay',
    linksUteis: [],
    roadmap: [],
    funcionalidades: [],
    releases: [],
    implementacoes: [],
    integracoes: [],
    equipe: [],
    createdAt: '2024-04-10T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'prod-log',
    codigo: 'FOCUS-LOG',
    nome: 'Focus Log',
    categoria: 'Logística',
    descricaoBreve: 'Módulo de gestão de frotas, cotação de fretes e rastreamento de entregas.',
    descricaoCompleta: 'Plataforma para gerenciamento de logística e expedição corporativa. Integra com transportadoras parceiras, calcula fretes e gera código de rastreamento para o cliente final.',
    status: 'Em Implantação',
    versaoAtual: 'v1.2.0',
    responsavelPrincipal: 'Lucas Mendes (Logistics Lead)',
    dataLancamento: '2024-11-01',
    siteOficial: 'https://focustecnologia.com.br/log',
    repositorioGit: 'https://github.com/focustecnologia/focus-log',
    linksUteis: [],
    roadmap: [],
    funcionalidades: [],
    releases: [],
    implementacoes: [],
    integracoes: [],
    equipe: [],
    createdAt: '2024-11-01T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'prod-ead',
    codigo: 'FOCUS-EAD',
    nome: 'Focus EAD',
    categoria: 'Educação / EAD',
    descricaoBreve: 'Plataforma LMS para treinamento interno de colaboradores e acervo de cursos para clientes.',
    descricaoCompleta: 'Central de aprendizagem corporativa. Permite disponibilizar vídeos, apostilas, quizzes e emissão automática de certificados para colaboradores e clientes.',
    status: 'Em Desenvolvimento',
    versaoAtual: 'v1.0.5',
    responsavelPrincipal: 'Juliana Costa (EdTech Lead)',
    dataLancamento: '2025-02-15',
    siteOficial: 'https://focustecnologia.com.br/ead',
    repositorioGit: 'https://github.com/focustecnologia/focus-ead',
    linksUteis: [],
    roadmap: [],
    funcionalidades: [],
    releases: [],
    implementacoes: [],
    integracoes: [],
    equipe: [],
    createdAt: '2025-02-15T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'prod-lab',
    codigo: 'FOCUS-LAB',
    nome: 'Focus Lab',
    categoria: 'Inovação & IA',
    descricaoBreve: 'Laboratório de Inteligência Artificial para OCR de Notas Fiscais e assistentes preditivos.',
    descricaoCompleta: 'Incubadora interna de projetos de IA generativa e machine learning. Responsável pelos copilotos inteligentes integrados no ecossistema Focus.',
    status: 'Em Desenvolvimento',
    versaoAtual: 'v0.9.0-beta',
    responsavelPrincipal: 'Dr. Paulo Nogueira (AI Researcher)',
    dataLancamento: '2025-05-01',
    siteOficial: 'https://focustecnologia.com.br/lab',
    repositorioGit: 'https://github.com/focustecnologia/focus-lab',
    linksUteis: [],
    roadmap: [],
    funcionalidades: [],
    releases: [],
    implementacoes: [],
    integracoes: [],
    equipe: [],
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
];
