import { ArtigoConhecimento, ChamadoSuporte } from './types';

export const DEFAULT_KB_ARTICLES: ArtigoConhecimento[] = [
  {
    id: 'kb-1',
    titulo: 'Como parametrizar a Emissão de NF-e e NFS-e no Focus ERP',
    categoria: 'ERP',
    resumo: 'Passo a passo completo para cadastrar certificados digitais A1/A3 e séries fiscais.',
    conteudo: 'Para configurar a emissão fiscal no Focus ERP: 1. Acesse Módulo Fiscal > Configurações. 2. Faça upload do certificado digital A1 (.pfx). 3. Informe a senha do certificado. 4. Preencha a série fiscal e a numeração do próximo lote. 5. Salve e execute um teste de validação de ambiente de homologação.',
    autor: 'Suporte Técnico Focus',
    visualizacoes: 142,
    utilidadeVotos: 38,
    tags: ['Fiscal', 'NF-e', 'NFS-e', 'ERP'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'kb-2',
    titulo: 'Integrando o Funil do Focus CRM com o Faturamento do ERP',
    categoria: 'CRM',
    resumo: 'Aprenda como transformar propostas ganhas no CRM em contratos e títulos no financeiro.',
    conteudo: 'No Focus CRM, ao mover uma oportunidade para a coluna "Fechado / Ganho", o sistema gera um evento Webhook automático enviando o contrato para a fila de faturamento do Focus ERP. Verifique se o cliente possui CNPJ e contato principal cadastrado.',
    autor: 'Equipe de CS',
    visualizacoes: 98,
    utilidadeVotos: 29,
    tags: ['CRM', 'ERP', 'Integrações', 'Vendas'],
    updatedAt: '2026-06-15',
  },
  {
    id: 'kb-3',
    titulo: 'Configurando Chaves PIX e Checkout Transparente no Focus Pay',
    categoria: 'Pay',
    resumo: 'Tutorial de habilitação de QR Code PIX dinâmico com conciliação bancária instantânea.',
    conteudo: 'Acesse Focus Pay > Integrações > Chaves PIX. Cadastre sua chave EVP ou CNPJ e insira o Webhook do seu banco parceiro para baixa automática dos títulos no módulo Contas a Receber.',
    autor: 'Fintech Lead',
    visualizacoes: 210,
    utilidadeVotos: 54,
    tags: ['PIX', 'Focus Pay', 'Financeiro'],
    updatedAt: '2026-07-10',
  },
  {
    id: 'kb-4',
    titulo: 'Como interpretar o Indicador EBITDA e DRE Gerencial no Focus BI',
    categoria: 'BI',
    resumo: 'Guia prático sobre o cálculo de margem operacional e visão de receitas recorrentes.',
    conteudo: 'O Focus BI calcula o EBITDA deduzindo do faturamento líquido todos os custos operacionais (CMV, salários, software e infraestrutura) antes dos impostos e amortizações.',
    autor: 'Data Analyst',
    visualizacoes: 175,
    utilidadeVotos: 41,
    tags: ['BI', 'DRE', 'EBITDA', 'Relatórios'],
    updatedAt: '2026-05-30',
  },
];

export const DEFAULT_TICKETS: ChamadoSuporte[] = [
  {
    id: 'tk-1001',
    numero: 'TK-1001',
    clienteId: 'cli-001',
    clienteNome: 'TechCorp Solutions Ltda',
    contatoNome: 'Carlos Andrade (CTO)',
    contatoEmail: 'carlos@techcorp.io',
    produtoId: 'prod-erp',
    produtoNome: 'Focus ERP',
    categoria: 'Financeiro & Fiscal',
    tipo: 'Bug',
    prioridade: 'Alta',
    responsavelNome: 'Ana Clara (Nível 2)',
    status: 'Em Atendimento',
    slaHorasPrimeiraResposta: 2,
    slaHorasResolucao: 8,
    dataAbertura: '2026-07-24T09:30:00.000Z',
    dataPrimeiraResposta: '2026-07-24T10:15:00.000Z',
    dataLimiteResolucao: '2026-07-24T17:30:00.000Z',
    slaStatus: 'Em Dia',
    titulo: 'Divergência na retenção de ISS na geração da NFS-e de São Paulo',
    descricao: 'Ao emitir nota fiscal de serviço para o tomador SP, o sistema não calculou a alíquota reduzida de 2% no arquivo XML.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tk-1002',
    numero: 'TK-1002',
    clienteId: 'cli-002',
    clienteNome: 'RetailFlex Logística & Varejo S.A.',
    contatoNome: 'Fernanda Lima (Head Ops)',
    contatoEmail: 'fernanda@retailflex.com.br',
    produtoId: 'prod-crm',
    produtoNome: 'Focus CRM',
    categoria: 'Automação Comercial',
    tipo: 'Nova Funcionalidade',
    prioridade: 'Média',
    responsavelNome: 'Lucas Mendes (Nível 1)',
    status: 'Em Desenvolvimento',
    slaHorasPrimeiraResposta: 4,
    slaHorasResolucao: 24,
    dataAbertura: '2026-07-23T14:00:00.000Z',
    dataPrimeiraResposta: '2026-07-23T15:20:00.000Z',
    dataLimiteResolucao: '2026-07-25T14:00:00.000Z',
    slaStatus: 'Em Dia',
    titulo: 'Solicitação de disparos sequenciais de WhatsApp na coluna Qualificação',
    descricao: 'Cliente solicita envio automático de mensagem 24h após a entrada do lead na etapa de qualificação.',
    devTaskId: 'bk-prod-crm-1',
    devTaskStatus: 'Em Desenvolvimento',
    devTaskTitulo: 'Automação de WhatsApp via Meta Cloud API',
    updatedAt: new Date().toISOString(),
  },
];
